var hierarchy =
[
    [ "filevault::cli::Application", "classfilevault_1_1cli_1_1Application.html", null ],
    [ "filevault::archive::ArchiveFormat", "classfilevault_1_1archive_1_1ArchiveFormat.html", null ],
    [ "filevault::core::Argon2Params", "structfilevault_1_1core_1_1Argon2Params.html", null ],
    [ "filevault::cli::AsymmetricBenchmarkResult", "structfilevault_1_1cli_1_1AsymmetricBenchmarkResult.html", null ],
    [ "filevault::cli::BenchmarkResult", "structfilevault_1_1cli_1_1BenchmarkResult.html", null ],
    [ "filevault::utils::BlockProgressBar", "classfilevault_1_1utils_1_1BlockProgressBar.html", null ],
    [ "filevault::core::ChunkInfo", "structfilevault_1_1core_1_1ChunkInfo.html", null ],
    [ "filevault::compression::CompressionResult", "structfilevault_1_1compression_1_1CompressionResult.html", null ],
    [ "filevault::compression::CompressionService", "classfilevault_1_1compression_1_1CompressionService.html", null ],
    [ "filevault::utils::Config", "classfilevault_1_1utils_1_1Config.html", null ],
    [ "filevault::utils::Console", "classfilevault_1_1utils_1_1Console.html", null ],
    [ "filevault::core::CryptoEngine", "classfilevault_1_1core_1_1CryptoEngine.html", null ],
    [ "filevault::core::CryptoResult", "structfilevault_1_1core_1_1CryptoResult.html", null ],
    [ "filevault::utils::CryptoUtils", "classfilevault_1_1utils_1_1CryptoUtils.html", null ],
    [ "filevault::algorithms::pqc::Dilithium", "classfilevault_1_1algorithms_1_1pqc_1_1Dilithium.html", null ],
    [ "filevault::algorithms::asymmetric::ECCKeyPair", "structfilevault_1_1algorithms_1_1asymmetric_1_1ECCKeyPair.html", null ],
    [ "filevault::algorithms::asymmetric::ECDH", "classfilevault_1_1algorithms_1_1asymmetric_1_1ECDH.html", null ],
    [ "filevault::algorithms::asymmetric::ECDHResult", "structfilevault_1_1algorithms_1_1asymmetric_1_1ECDHResult.html", null ],
    [ "filevault::algorithms::asymmetric::ECDSA", "classfilevault_1_1algorithms_1_1asymmetric_1_1ECDSA.html", null ],
    [ "filevault::algorithms::asymmetric::ECDSASignResult", "structfilevault_1_1algorithms_1_1asymmetric_1_1ECDSASignResult.html", null ],
    [ "filevault::core::EncryptionConfig", "structfilevault_1_1core_1_1EncryptionConfig.html", null ],
    [ "filevault::archive::FileEntry", "structfilevault_1_1archive_1_1FileEntry.html", null ],
    [ "filevault::core::FileFormatHandler", "classfilevault_1_1core_1_1FileFormatHandler.html", null ],
    [ "filevault::core::FileHeader", "structfilevault_1_1core_1_1FileHeader.html", null ],
    [ "filevault::format::FileHeader", "classfilevault_1_1format_1_1FileHeader.html", null ],
    [ "filevault::cli::InfoCommand::FileInfo", "structfilevault_1_1cli_1_1InfoCommand_1_1FileInfo.html", null ],
    [ "filevault::utils::FileIO", "classfilevault_1_1utils_1_1FileIO.html", null ],
    [ "filevault::core::HashConfig", "structfilevault_1_1core_1_1HashConfig.html", null ],
    [ "filevault::cli::ICommand", "classfilevault_1_1cli_1_1ICommand.html", [
      [ "filevault::cli::BenchmarkCommand", "classfilevault_1_1cli_1_1BenchmarkCommand.html", null ],
      [ "filevault::cli::CompressCommand", "classfilevault_1_1cli_1_1CompressCommand.html", null ],
      [ "filevault::cli::ConfigCommand", "classfilevault_1_1cli_1_1ConfigCommand.html", null ],
      [ "filevault::cli::DecompressCommand", "classfilevault_1_1cli_1_1DecompressCommand.html", null ],
      [ "filevault::cli::DecryptCommand", "classfilevault_1_1cli_1_1DecryptCommand.html", null ],
      [ "filevault::cli::EncryptCommand", "classfilevault_1_1cli_1_1EncryptCommand.html", null ],
      [ "filevault::cli::HashCommand", "classfilevault_1_1cli_1_1HashCommand.html", null ],
      [ "filevault::cli::InfoCommand", "classfilevault_1_1cli_1_1InfoCommand.html", null ],
      [ "filevault::cli::KeygenCommand", "classfilevault_1_1cli_1_1KeygenCommand.html", null ],
      [ "filevault::cli::ListCommand", "classfilevault_1_1cli_1_1ListCommand.html", null ],
      [ "filevault::cli::commands::ArchiveCommand", "classfilevault_1_1cli_1_1commands_1_1ArchiveCommand.html", null ],
      [ "filevault::cli::commands::DumpCommand", "classfilevault_1_1cli_1_1commands_1_1DumpCommand.html", null ],
      [ "filevault::cli::commands::KeyInfoCommand", "classfilevault_1_1cli_1_1commands_1_1KeyInfoCommand.html", null ],
      [ "filevault::cli::commands::SignCommand", "classfilevault_1_1cli_1_1commands_1_1SignCommand.html", null ],
      [ "filevault::cli::commands::StegoCommand", "classfilevault_1_1cli_1_1commands_1_1StegoCommand.html", null ],
      [ "filevault::cli::commands::VerifyCommand", "classfilevault_1_1cli_1_1commands_1_1VerifyCommand.html", null ]
    ] ],
    [ "filevault::compression::ICompressor", "classfilevault_1_1compression_1_1ICompressor.html", [
      [ "filevault::compression::Bzip2Compressor", "classfilevault_1_1compression_1_1Bzip2Compressor.html", null ],
      [ "filevault::compression::LzmaCompressor", "classfilevault_1_1compression_1_1LzmaCompressor.html", null ],
      [ "filevault::compression::ZlibCompressor", "classfilevault_1_1compression_1_1ZlibCompressor.html", null ]
    ] ],
    [ "filevault::core::ICryptoAlgorithm", "classfilevault_1_1core_1_1ICryptoAlgorithm.html", [
      [ "filevault::algorithms::asymmetric::ECCHybrid", "classfilevault_1_1algorithms_1_1asymmetric_1_1ECCHybrid.html", null ],
      [ "filevault::algorithms::asymmetric::RSA", "classfilevault_1_1algorithms_1_1asymmetric_1_1RSA.html", null ],
      [ "filevault::algorithms::classical::Caesar", "classfilevault_1_1algorithms_1_1classical_1_1Caesar.html", null ],
      [ "filevault::algorithms::classical::Caesar", "classfilevault_1_1algorithms_1_1classical_1_1Caesar.html", null ],
      [ "filevault::algorithms::classical::HillCipher", "classfilevault_1_1algorithms_1_1classical_1_1HillCipher.html", null ],
      [ "filevault::algorithms::classical::Playfair", "classfilevault_1_1algorithms_1_1classical_1_1Playfair.html", null ],
      [ "filevault::algorithms::classical::Playfair", "classfilevault_1_1algorithms_1_1classical_1_1Playfair.html", null ],
      [ "filevault::algorithms::classical::SubstitutionCipher", "classfilevault_1_1algorithms_1_1classical_1_1SubstitutionCipher.html", null ],
      [ "filevault::algorithms::classical::Vigenere", "classfilevault_1_1algorithms_1_1classical_1_1Vigenere.html", null ],
      [ "filevault::algorithms::classical::Vigenere", "classfilevault_1_1algorithms_1_1classical_1_1Vigenere.html", null ],
      [ "filevault::algorithms::pqc::Kyber", "classfilevault_1_1algorithms_1_1pqc_1_1Kyber.html", null ],
      [ "filevault::algorithms::pqc::KyberHybrid", "classfilevault_1_1algorithms_1_1pqc_1_1KyberHybrid.html", null ],
      [ "filevault::algorithms::symmetric::AES_CBC", "classfilevault_1_1algorithms_1_1symmetric_1_1AES__CBC.html", null ],
      [ "filevault::algorithms::symmetric::AES_CFB", "classfilevault_1_1algorithms_1_1symmetric_1_1AES__CFB.html", null ],
      [ "filevault::algorithms::symmetric::AES_CTR", "classfilevault_1_1algorithms_1_1symmetric_1_1AES__CTR.html", null ],
      [ "filevault::algorithms::symmetric::AES_ECB", "classfilevault_1_1algorithms_1_1symmetric_1_1AES__ECB.html", null ],
      [ "filevault::algorithms::symmetric::AES_GCM", "classfilevault_1_1algorithms_1_1symmetric_1_1AES__GCM.html", null ],
      [ "filevault::algorithms::symmetric::AES_OFB", "classfilevault_1_1algorithms_1_1symmetric_1_1AES__OFB.html", null ],
      [ "filevault::algorithms::symmetric::AES_XTS", "classfilevault_1_1algorithms_1_1symmetric_1_1AES__XTS.html", null ],
      [ "filevault::algorithms::symmetric::ARIA_GCM", "classfilevault_1_1algorithms_1_1symmetric_1_1ARIA__GCM.html", null ],
      [ "filevault::algorithms::symmetric::Camellia_GCM", "classfilevault_1_1algorithms_1_1symmetric_1_1Camellia__GCM.html", null ],
      [ "filevault::algorithms::symmetric::ChaCha20Poly1305", "classfilevault_1_1algorithms_1_1symmetric_1_1ChaCha20Poly1305.html", null ],
      [ "filevault::algorithms::symmetric::SM4_GCM", "classfilevault_1_1algorithms_1_1symmetric_1_1SM4__GCM.html", null ],
      [ "filevault::algorithms::symmetric::Serpent_GCM", "classfilevault_1_1algorithms_1_1symmetric_1_1Serpent__GCM.html", null ],
      [ "filevault::algorithms::symmetric::TripleDES", "classfilevault_1_1algorithms_1_1symmetric_1_1TripleDES.html", null ],
      [ "filevault::algorithms::symmetric::Twofish_GCM", "classfilevault_1_1algorithms_1_1symmetric_1_1Twofish__GCM.html", null ]
    ] ],
    [ "filevault::steganography::LSBSteganography", "classfilevault_1_1steganography_1_1LSBSteganography.html", null ],
    [ "filevault::core::ModePreset", "structfilevault_1_1core_1_1ModePreset.html", null ],
    [ "filevault::utils::Password", "classfilevault_1_1utils_1_1Password.html", null ],
    [ "filevault::core::PasswordAnalysis", "structfilevault_1_1core_1_1PasswordAnalysis.html", null ],
    [ "filevault::core::PBKDF2Params", "structfilevault_1_1core_1_1PBKDF2Params.html", null ],
    [ "filevault::cli::PQCBenchmarkResult", "structfilevault_1_1cli_1_1PQCBenchmarkResult.html", null ],
    [ "filevault::algorithms::pqc::PQKeyPair", "structfilevault_1_1algorithms_1_1pqc_1_1PQKeyPair.html", null ],
    [ "filevault::utils::ProgressBar", "classfilevault_1_1utils_1_1ProgressBar.html", null ],
    [ "filevault::core::Result< T >", "structfilevault_1_1core_1_1Result.html", null ],
    [ "filevault::core::Result< void >", "structfilevault_1_1core_1_1Result_3_01void_01_4.html", null ],
    [ "filevault::algorithms::asymmetric::RSAKeyPair", "structfilevault_1_1algorithms_1_1asymmetric_1_1RSAKeyPair.html", null ],
    [ "filevault::core::ScryptParams", "structfilevault_1_1core_1_1ScryptParams.html", null ],
    [ "filevault::cli::SignatureBenchmarkResult", "structfilevault_1_1cli_1_1SignatureBenchmarkResult.html", null ],
    [ "filevault::core::StreamingConfig", "structfilevault_1_1core_1_1StreamingConfig.html", null ],
    [ "filevault::core::StreamingCrypto", "classfilevault_1_1core_1_1StreamingCrypto.html", null ],
    [ "filevault::core::StreamingResult", "structfilevault_1_1core_1_1StreamingResult.html", null ],
    [ "filevault::utils::TableBuilder", "classfilevault_1_1utils_1_1TableBuilder.html", null ],
    [ "filevault::utils::TableFormatter", "classfilevault_1_1utils_1_1TableFormatter.html", null ]
];